### ISSUE TITLE
RateLimitExceeded

### ISSUE THREAD

**Issue by ValvojaX** [csgofloat/CSGOFloat-Inspect#73]
I got more accounts and now getting this error for all the accounts:

error: Error logging in xxxxxxx: message=RateLimitExceeded, stack=Error: RateLimitExceeded
    at SteamUser._handlers.<computed> (C:\Users\user\Desktop\project\FloatDB\node_modules\steam-user\components\logon.js:363:16)
    at SteamUser._handleMessage (C:\Users\user\Desktop\project\FloatDB\node_modules\steam-user\components\messages.js:249:30)
    at CMClient.emit (events.js:327:22)
    at CMClient._netMsgReceived (C:\Users\user\Desktop\project\FloatDB\node_modules\steam-client\lib\cm_client.js:323:8)
    at CMClient.handlers.<computed> (C:\Users\user\Desktop\procect\FloatDB\node_modules\steam-client\lib\cm_client.js:609:8)
    at CMClient._netMsgReceived (C:\Users\user\Desktop\project\FloatDB\node_modules\steam-client\lib\cm_client.js:305:24)
    at TCPConnection.emit (events.js:315:20)
    at TCPConnection._readPacket (C:\Users\user\Desktop\project\FloatDB\node_modules\steam-client\lib\tcp_connection.js:183:7)
    at Socket.emit (events.js:315:20)
    at emitReadable_ (_stream_readable.js:556:12), eresult=84

**Comment by Step7750** [comment]
This isn't an issue with the library, you're hitting something on Steam's end. Possibly generating too many failed logins at once, or logging in too many new accounts without sentries.
